fix for is_shipping_required when basket is unset
django-1                         | *** basket_id: 13222
django-1                         | *** Unable to load frozen basket with ID 13222
django-1                         | *** shipping_code: no-shipping-required
django-1                         | Internal Server Error: /products/checkout/webhook/
django-1                         | Traceback (most recent call last):
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
django-1                         |     response = get_response(request)
django-1                         |                ^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
django-1                         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-1                         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
django-1                         |     return self.dispatch(request, *args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
django-1                         |     return bound_method(*args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
django-1                         |     return view_func(request, *args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/oscar_stripe_sca/mixins.py", line 42, in dispatch
django-1                         |     return super().dispatch(*args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/oscar/apps/checkout/session.py", line 68, in dispatch
django-1                         |     return super().dispatch(request, *args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
django-1                         |     return handler(request, *args, **kwargs)
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/oscar_stripe_sca/views.py", line 305, in post
django-1                         |     shipping_method = self.get_shipping_method_by_code(
django-1                         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/oscar_stripe_sca/mixins.py", line 150, in get_shipping_method_by_code
django-1                         |     shipping_methods = ShippingRepository().get_shipping_methods(basket)
django-1                         |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         |   File "/usr/local/lib/python3.11/site-packages/oscar/apps/shipping/repository.py", line 42, in get_shipping_methods
django-1                         |     if not basket.is_shipping_required():
django-1                         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1                         | AttributeError: 'NoneType' object has no attribute 'is_shipping_required'
django-1                         | [07/Sep/2026 10:23:46] "POST /products/checkout/webhook/ HTTP/1.1" 500 31090